/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sniffer;

import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author Diego EG
 */
public class Inicio extends javax.swing.JFrame {

    private int tiempo = 90;
    private int numPaquetes = 10;
    private int modo = 1;
    private int tamPaquetes = 200;
    private File archivo;
    private String filtros[];

    public void setTiempo(int tiempo) {
        this.tiempo = tiempo;
    }

    public void setNumPaquetes(int numPaquetes) {
        this.numPaquetes = numPaquetes;
    }

    public void setModo(int modo) {
        this.modo = modo;
    }

    public void setTamPaquetes(int tamPaquetes) {
        this.tamPaquetes = tamPaquetes;
    }
     
    public Inicio() {
        initComponents();
        
        this.jcbModo.removeAllItems();
        DefaultListModel listaModo = new DefaultListModel();
        this.filtros = new String[2];
        this.jPanelFiltrosETHERNET.setVisible(false);
        this.jcbModo.addItem("Promiscuo");
        this.jcbModo.addItem("No Promiscuo");
        this.jcbModo.addItem("Bloqueo");
        this.jcbModo.addItem("No Bloqueo");
        

        this.jPanelVueloArchivo.setVisible(false);
        this.jPanelParametros.setVisible(false);
        this.jPanleFiltros.setVisible(false);
                
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAnalizarGenerar = new javax.swing.ButtonGroup();
        bgVueloCargarArchivo = new javax.swing.ButtonGroup();
        jbgETHERNETIEEE = new javax.swing.ButtonGroup();
        bgOpcionesETHERNET = new javax.swing.ButtonGroup();
        lblIPN = new javax.swing.JLabel();
        lblESCOM = new javax.swing.JLabel();
        lblSniffer = new javax.swing.JLabel();
        lblEGD = new javax.swing.JLabel();
        lblOVI = new javax.swing.JLabel();
        lbl2CV10 = new javax.swing.JLabel();
        lblInstrucciones1 = new javax.swing.JLabel();
        jrbAnalizarTramas = new javax.swing.JRadioButton();
        jrbGenerarTramas = new javax.swing.JRadioButton();
        jPanelVueloArchivo = new javax.swing.JPanel();
        jrbArchivo = new javax.swing.JRadioButton();
        jrbVuelo = new javax.swing.JRadioButton();
        jPanelParametros = new javax.swing.JPanel();
        jlParametros = new javax.swing.JLabel();
        jlTiempo = new javax.swing.JLabel();
        jlNumPaquetes = new javax.swing.JLabel();
        jlModo = new javax.swing.JLabel();
        jlTamMax = new javax.swing.JLabel();
        jtfTiempo = new javax.swing.JTextField();
        jtfNumPaquetes = new javax.swing.JTextField();
        jcbModo = new javax.swing.JComboBox<>();
        jtfTamMax = new javax.swing.JTextField();
        jPanleFiltros = new javax.swing.JPanel();
        jlFiltrosCaptura = new javax.swing.JLabel();
        jrbETHERNET = new javax.swing.JRadioButton();
        jrbIEE802 = new javax.swing.JRadioButton();
        jPanelFiltrosETHERNET = new javax.swing.JPanel();
        jrbARP = new javax.swing.JRadioButton();
        jrbIP = new javax.swing.JRadioButton();
        jrbTCP = new javax.swing.JRadioButton();
        jrbUDP = new javax.swing.JRadioButton();
        jrbICMP = new javax.swing.JRadioButton();
        jbAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlLogoIPN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sniffer Redes de Computadoras");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 204, 255));
        setResizable(false);

        lblIPN.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblIPN.setText("Instituo Politécnico Nacional");

        lblESCOM.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblESCOM.setText("Escuela Superior de Cómputo");

        lblSniffer.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblSniffer.setText("Proyecto de redes de computadoras: Sniffer");

        lblEGD.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblEGD.setText("Estrada Granados Diego");

        lblOVI.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblOVI.setText("Ortega Victoriano Ivan");

        lbl2CV10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lbl2CV10.setText("Grupo: 2cv10");

        lblInstrucciones1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        lblInstrucciones1.setText("Selecciona una opción a ser ejecutada.");

        bgAnalizarGenerar.add(jrbAnalizarTramas);
        jrbAnalizarTramas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbAnalizarTramas.setText("Analizar Tramas");
        jrbAnalizarTramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAnalizarTramasActionPerformed(evt);
            }
        });

        bgAnalizarGenerar.add(jrbGenerarTramas);
        jrbGenerarTramas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbGenerarTramas.setText("Generar Tramas");
        jrbGenerarTramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGenerarTramasActionPerformed(evt);
            }
        });

        bgVueloCargarArchivo.add(jrbArchivo);
        jrbArchivo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbArchivo.setSelected(true);
        jrbArchivo.setText("Cargar de Archivo");

        bgVueloCargarArchivo.add(jrbVuelo);
        jrbVuelo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbVuelo.setText("Al vuelo");

        javax.swing.GroupLayout jPanelVueloArchivoLayout = new javax.swing.GroupLayout(jPanelVueloArchivo);
        jPanelVueloArchivo.setLayout(jPanelVueloArchivoLayout);
        jPanelVueloArchivoLayout.setHorizontalGroup(
            jPanelVueloArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVueloArchivoLayout.createSequentialGroup()
                .addComponent(jrbVuelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jrbArchivo)
                .addGap(26, 26, 26))
        );
        jPanelVueloArchivoLayout.setVerticalGroup(
            jPanelVueloArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVueloArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVueloArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbArchivo)
                    .addComponent(jrbVuelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlParametros.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jlParametros.setText("Especifica los parametros del paquete a capturar");

        jlTiempo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jlTiempo.setText("Tiempo (Segundos)");

        jlNumPaquetes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jlNumPaquetes.setText("Número de paquetes");

        jlModo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jlModo.setText("Modo");

        jlTamMax.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jlTamMax.setText("Tamaño máximo (bytes)");

        jtfTiempo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtfTiempo.setText("10");
        jtfTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTiempoActionPerformed(evt);
            }
        });

        jtfNumPaquetes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtfNumPaquetes.setText("10");

        jcbModo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jcbModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtfTamMax.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtfTamMax.setText("200");

        javax.swing.GroupLayout jPanelParametrosLayout = new javax.swing.GroupLayout(jPanelParametros);
        jPanelParametros.setLayout(jPanelParametrosLayout);
        jPanelParametrosLayout.setHorizontalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTiempo)
                    .addComponent(jlNumPaquetes)
                    .addComponent(jlParametros)
                    .addComponent(jlModo)
                    .addComponent(jlTamMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfNumPaquetes, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addComponent(jtfTiempo))
                    .addComponent(jcbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTamMax, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
        jPanelParametrosLayout.setVerticalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlParametros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTiempo)
                    .addComponent(jtfTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumPaquetes)
                    .addComponent(jtfNumPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlModo)
                    .addComponent(jcbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTamMax)
                    .addComponent(jtfTamMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jlFiltrosCaptura.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jlFiltrosCaptura.setText("Selecciona los filtros de captura ");

        jbgETHERNETIEEE.add(jrbETHERNET);
        jrbETHERNET.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbETHERNET.setText("ETHERNET");
        jrbETHERNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbETHERNETActionPerformed(evt);
            }
        });

        jbgETHERNETIEEE.add(jrbIEE802);
        jrbIEE802.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbIEE802.setText("IEEE 802.3");
        jrbIEE802.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIEE802ActionPerformed(evt);
            }
        });

        bgOpcionesETHERNET.add(jrbARP);
        jrbARP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbARP.setText("ARP");

        bgOpcionesETHERNET.add(jrbIP);
        jrbIP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbIP.setText("IP");
        jrbIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIPActionPerformed(evt);
            }
        });

        bgOpcionesETHERNET.add(jrbTCP);
        jrbTCP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbTCP.setText("TCP");

        bgOpcionesETHERNET.add(jrbUDP);
        jrbUDP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbUDP.setText("UDP");

        bgOpcionesETHERNET.add(jrbICMP);
        jrbICMP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jrbICMP.setText("ICMP");

        javax.swing.GroupLayout jPanelFiltrosETHERNETLayout = new javax.swing.GroupLayout(jPanelFiltrosETHERNET);
        jPanelFiltrosETHERNET.setLayout(jPanelFiltrosETHERNETLayout);
        jPanelFiltrosETHERNETLayout.setHorizontalGroup(
            jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosETHERNETLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbIP)
                    .addComponent(jrbARP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbUDP)
                    .addComponent(jrbTCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbICMP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFiltrosETHERNETLayout.setVerticalGroup(
            jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosETHERNETLayout.createSequentialGroup()
                .addGroup(jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltrosETHERNETLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbIP)
                            .addComponent(jrbTCP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbARP)
                            .addComponent(jrbUDP)))
                    .addGroup(jPanelFiltrosETHERNETLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jrbICMP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanleFiltrosLayout = new javax.swing.GroupLayout(jPanleFiltros);
        jPanleFiltros.setLayout(jPanleFiltrosLayout);
        jPanleFiltrosLayout.setHorizontalGroup(
            jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbIEE802)
                    .addComponent(jrbETHERNET))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanelFiltrosETHERNET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                .addComponent(jlFiltrosCaptura)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanleFiltrosLayout.setVerticalGroup(
            jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFiltrosCaptura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                        .addComponent(jrbETHERNET)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbIEE802))
                    .addComponent(jPanelFiltrosETHERNET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jbAceptar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoescom-iloveimg-resized (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jlLogoIPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logipn-iloveimg-resized (1).png"))); // NOI18N
        jlLogoIPN.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelVueloArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlLogoIPN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblESCOM)
                                            .addComponent(lblIPN))
                                        .addGap(76, 76, 76))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblSniffer)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblOVI)
                                            .addComponent(lblEGD))
                                        .addGap(94, 94, 94)))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbGenerarTramas)
                                        .addGap(135, 135, 135)
                                        .addComponent(jrbAnalizarTramas))
                                    .addComponent(lblInstrucciones1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanleFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)
                                        .addComponent(jbAceptar)))
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(lbl2CV10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIPN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblESCOM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSniffer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEGD)))
                        .addGap(6, 6, 6)
                        .addComponent(lblOVI)
                        .addGap(11, 11, 11)
                        .addComponent(lbl2CV10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInstrucciones1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbAnalizarTramas)
                            .addComponent(jrbGenerarTramas)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlLogoIPN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelVueloArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanleFiltros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbETHERNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbETHERNETActionPerformed
        jPanelFiltrosETHERNET.setVisible(true);
    }//GEN-LAST:event_jrbETHERNETActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        
        cargarParametros();
       
        
        if(this.jrbAnalizarTramas.isSelected())
        {
             if (this.jrbArchivo.isSelected() && this.jrbAnalizarTramas.isSelected())
            {
                JFileChooser abrirArchivo = new JFileChooser();
                FileNameExtensionFilter extension = new FileNameExtensionFilter("archivos pcap (*.pcap)", "pcap");
                abrirArchivo.setFileFilter(extension);
                abrirArchivo.setDialogTitle("Abrir archivo");
                // set selected filter
                abrirArchivo.setFileFilter(extension);
      
                int resultado = abrirArchivo.showOpenDialog(null);
                archivo = abrirArchivo.getSelectedFile();
                if(resultado==JFileChooser.APPROVE_OPTION){
                    System.out.println("Archivo seleccionado: "+archivo.getAbsolutePath()); //JOPTION
                    
                }
            }
            else{
                archivo = null;}
             
        AnalizarTramas formularioAnalizarTramas = new AnalizarTramas(this.archivo,this.tiempo, this.numPaquetes, this.modo, this.tamPaquetes,this.filtros); 
        formularioAnalizarTramas.setVisible(true);
        this.setVisible(false);
            
        }
        else
        {
            if(this.jrbGenerarTramas.isSelected())
            {
                GenerarTramas formularioGT = new GenerarTramas();
                formularioGT.setVisible(true);
                this.setVisible(false);
            }
            else
                System.out.println("Selecciona una opcion "); //JOPTION
        }
        
       
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jrbIEE802ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIEE802ActionPerformed
        this.jPanelFiltrosETHERNET.setVisible(false);
    }//GEN-LAST:event_jrbIEE802ActionPerformed

    private void jtfTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTiempoActionPerformed

    private void jrbAnalizarTramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAnalizarTramasActionPerformed
        this.jPanelVueloArchivo.setVisible(true);
        this.jPanelParametros.setVisible(true);
        this.jPanleFiltros.setVisible(true);
    }//GEN-LAST:event_jrbAnalizarTramasActionPerformed

    private void jrbGenerarTramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGenerarTramasActionPerformed
        this.jPanelVueloArchivo.setVisible(false);
        this.jPanelParametros.setVisible(false);
        this.jPanleFiltros.setVisible(false);
    }//GEN-LAST:event_jrbGenerarTramasActionPerformed

    private void jrbIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbIPActionPerformed

    public void cargarParametros()
    {
        
        this.tiempo = Integer.parseInt(this.jtfTiempo.getText());
        this.numPaquetes = Integer.valueOf(this.jtfNumPaquetes.getText());
        this.tamPaquetes = Integer.parseInt(this.jtfTamMax.getText());
        this.modo = this.jcbModo.getSelectedIndex();
        this.filtros[0] = null;
        this.filtros[1] = null;
        
        if(this.jrbIEE802.isSelected())
        {
            this.filtros[0] = "ieee";
        }
        else
        {
            if(this.jrbETHERNET.isSelected())
                this.filtros[0] = "ethernet";
            else{
                    if(this.jrbIP.isSelected()){
                        this.filtros[1] = "ipv4";
                    }
                    if(this.jrbARP.isSelected()){
                        this.filtros[1] = "arp";
                    }
                    if(this.jrbTCP.isSelected()){
                        this.filtros[1] = "tcp";
                    }
                    if(this.jrbUDP.isSelected()){
                        this.filtros[1] = "udp";
                    }
                    if(this.jrbICMP.isSelected()){
                        this.filtros[1] = "icmp";
                    }
            }
            
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAnalizarGenerar;
    private javax.swing.ButtonGroup bgOpcionesETHERNET;
    private javax.swing.ButtonGroup bgVueloCargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFiltrosETHERNET;
    private javax.swing.JPanel jPanelParametros;
    private javax.swing.JPanel jPanelVueloArchivo;
    private javax.swing.JPanel jPanleFiltros;
    private javax.swing.JButton jbAceptar;
    private javax.swing.ButtonGroup jbgETHERNETIEEE;
    private javax.swing.JComboBox<String> jcbModo;
    private javax.swing.JLabel jlFiltrosCaptura;
    private javax.swing.JLabel jlLogoIPN;
    private javax.swing.JLabel jlModo;
    private javax.swing.JLabel jlNumPaquetes;
    private javax.swing.JLabel jlParametros;
    private javax.swing.JLabel jlTamMax;
    private javax.swing.JLabel jlTiempo;
    private javax.swing.JRadioButton jrbARP;
    private javax.swing.JRadioButton jrbAnalizarTramas;
    private javax.swing.JRadioButton jrbArchivo;
    private javax.swing.JRadioButton jrbETHERNET;
    private javax.swing.JRadioButton jrbGenerarTramas;
    private javax.swing.JRadioButton jrbICMP;
    private javax.swing.JRadioButton jrbIEE802;
    private javax.swing.JRadioButton jrbIP;
    private javax.swing.JRadioButton jrbTCP;
    private javax.swing.JRadioButton jrbUDP;
    private javax.swing.JRadioButton jrbVuelo;
    private javax.swing.JTextField jtfNumPaquetes;
    private javax.swing.JTextField jtfTamMax;
    private javax.swing.JTextField jtfTiempo;
    private javax.swing.JLabel lbl2CV10;
    private javax.swing.JLabel lblEGD;
    private javax.swing.JLabel lblESCOM;
    private javax.swing.JLabel lblIPN;
    private javax.swing.JLabel lblInstrucciones1;
    private javax.swing.JLabel lblOVI;
    private javax.swing.JLabel lblSniffer;
    // End of variables declaration//GEN-END:variables
}
