/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sniffer;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author Diego EG
 */
public class Inicio extends javax.swing.JFrame {

    private int tiempo = 90;
    private int numPaquetes = 10;
    private int modo = 1;
    private int tamPaquetes = 200;
    private File archivo;
     
    public Inicio() {
        initComponents();
        
        this.jcbModo.removeAllItems();
        DefaultListModel listaModo = new DefaultListModel();
        this.jcbModo.addItem("Promiscuo");
        this.jcbModo.addItem("No Promiscuo");
        this.jcbModo.addItem("Bloqueo");
        this.jcbModo.addItem("No Bloqueo");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAnalizarGenerar = new javax.swing.ButtonGroup();
        bgVueloCargarArchivo = new javax.swing.ButtonGroup();
        jbgETHERNETIEEE = new javax.swing.ButtonGroup();
        bgOpcionesETHERNET = new javax.swing.ButtonGroup();
        lblIPN = new javax.swing.JLabel();
        lblESCOM = new javax.swing.JLabel();
        lblSniffer = new javax.swing.JLabel();
        lblEGD = new javax.swing.JLabel();
        lblOVI = new javax.swing.JLabel();
        lbl2CV10 = new javax.swing.JLabel();
        lblInstrucciones1 = new javax.swing.JLabel();
        jrbAnalizarTramas = new javax.swing.JRadioButton();
        jrbGenerarTramas = new javax.swing.JRadioButton();
        jPanelVueloArchivo = new javax.swing.JPanel();
        jrbVuelo = new javax.swing.JRadioButton();
        jrbArchivo = new javax.swing.JRadioButton();
        jPanelParametros = new javax.swing.JPanel();
        jlParametros = new javax.swing.JLabel();
        jlTiempo = new javax.swing.JLabel();
        jlNumPaquetes = new javax.swing.JLabel();
        jlModo = new javax.swing.JLabel();
        jlTamMax = new javax.swing.JLabel();
        jtfTiempo = new javax.swing.JTextField();
        jtfNumPaquetes = new javax.swing.JTextField();
        jcbModo = new javax.swing.JComboBox<>();
        jtfTamMax = new javax.swing.JTextField();
        jPanleFiltros = new javax.swing.JPanel();
        jlFiltrosCaptura = new javax.swing.JLabel();
        jrbETHERNET = new javax.swing.JRadioButton();
        jrbIEE802 = new javax.swing.JRadioButton();
        jPanelFiltrosETHERNET = new javax.swing.JPanel();
        jrbARP = new javax.swing.JRadioButton();
        jrbIP = new javax.swing.JRadioButton();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        lblIPN.setText("Instituo Politécnico Nacional");

        lblESCOM.setText("Escuela Superior de Cómputo");

        lblSniffer.setText("Proyecto de redes de computadoras: Sniffer");

        lblEGD.setText("Estrada Granados Diego");

        lblOVI.setText("Ortega Victoriano Ivan");

        lbl2CV10.setText("Grupo: 2CV10");

        lblInstrucciones1.setText("Selecciona una opción a ser ejecutada.");

        bgAnalizarGenerar.add(jrbAnalizarTramas);
        jrbAnalizarTramas.setText("Analizar Tramas");

        bgAnalizarGenerar.add(jrbGenerarTramas);
        jrbGenerarTramas.setText("Generar Tramas");

        bgVueloCargarArchivo.add(jrbVuelo);
        jrbVuelo.setText("Al vuelo");

        bgVueloCargarArchivo.add(jrbArchivo);
        jrbArchivo.setSelected(true);
        jrbArchivo.setText("Cargar de Archivo");

        javax.swing.GroupLayout jPanelVueloArchivoLayout = new javax.swing.GroupLayout(jPanelVueloArchivo);
        jPanelVueloArchivo.setLayout(jPanelVueloArchivoLayout);
        jPanelVueloArchivoLayout.setHorizontalGroup(
            jPanelVueloArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVueloArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbVuelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jrbArchivo)
                .addContainerGap())
        );
        jPanelVueloArchivoLayout.setVerticalGroup(
            jPanelVueloArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVueloArchivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelVueloArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbVuelo)
                    .addComponent(jrbArchivo)))
        );

        jlParametros.setText("Especifica los parametros del paquete a capturar");

        jlTiempo.setText("Tiempo (Segundos)");

        jlNumPaquetes.setText("Número de paquetes");

        jlModo.setText("Modo");

        jlTamMax.setText("Tamaño máximo (bytes)");

        jtfTiempo.setText("90");

        jtfNumPaquetes.setText("10");

        jcbModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtfTamMax.setText("200");

        javax.swing.GroupLayout jPanelParametrosLayout = new javax.swing.GroupLayout(jPanelParametros);
        jPanelParametros.setLayout(jPanelParametrosLayout);
        jPanelParametrosLayout.setHorizontalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTiempo)
                    .addComponent(jlNumPaquetes)
                    .addComponent(jlParametros)
                    .addComponent(jlModo)
                    .addComponent(jlTamMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfNumPaquetes, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addComponent(jtfTiempo))
                    .addComponent(jcbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTamMax, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
        jPanelParametrosLayout.setVerticalGroup(
            jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlParametros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTiempo)
                    .addComponent(jtfTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumPaquetes)
                    .addComponent(jtfNumPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlModo)
                    .addComponent(jcbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTamMax)
                    .addComponent(jtfTamMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jlFiltrosCaptura.setText("Selecciona los filtros de captura ");

        jbgETHERNETIEEE.add(jrbETHERNET);
        jrbETHERNET.setText("ETHERNET");
        jrbETHERNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbETHERNETActionPerformed(evt);
            }
        });

        jbgETHERNETIEEE.add(jrbIEE802);
        jrbIEE802.setText("IEEE 802.3");

        bgOpcionesETHERNET.add(jrbARP);
        jrbARP.setText("ARP");

        bgOpcionesETHERNET.add(jrbIP);
        jrbIP.setText("IP");

        javax.swing.GroupLayout jPanelFiltrosETHERNETLayout = new javax.swing.GroupLayout(jPanelFiltrosETHERNET);
        jPanelFiltrosETHERNET.setLayout(jPanelFiltrosETHERNETLayout);
        jPanelFiltrosETHERNETLayout.setHorizontalGroup(
            jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosETHERNETLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbIP)
                    .addComponent(jrbARP))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanelFiltrosETHERNETLayout.setVerticalGroup(
            jPanelFiltrosETHERNETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosETHERNETLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbARP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanleFiltrosLayout = new javax.swing.GroupLayout(jPanleFiltros);
        jPanleFiltros.setLayout(jPanleFiltrosLayout);
        jPanleFiltrosLayout.setHorizontalGroup(
            jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                        .addComponent(jlFiltrosCaptura)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                        .addGroup(jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbIEE802)
                            .addComponent(jrbETHERNET))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelFiltrosETHERNET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        jPanleFiltrosLayout.setVerticalGroup(
            jPanleFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFiltrosCaptura)
                .addGap(18, 18, 18)
                .addComponent(jrbETHERNET)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbIEE802)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanleFiltrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFiltrosETHERNET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblESCOM)
                            .addComponent(lblIPN))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbGenerarTramas)
                                        .addGap(119, 119, 119)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEGD)
                                            .addComponent(lblOVI)
                                            .addComponent(jrbAnalizarTramas)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanelVueloArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addGap(49, 49, 49)
                                .addComponent(lbl2CV10))
                            .addComponent(lblInstrucciones1)
                            .addComponent(jPanelParametros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanleFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAceptar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSniffer)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblIPN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblESCOM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSniffer)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEGD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOVI))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl2CV10)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInstrucciones1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbAnalizarTramas)
                            .addComponent(jrbGenerarTramas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelVueloArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanelParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanleFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAceptar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        
        if (this.jrbArchivo.isSelected() && this.jrbAnalizarTramas.isSelected())
        {
            JFileChooser abrirArchivo = new JFileChooser();
            FileNameExtensionFilter extension = new FileNameExtensionFilter("archivos pcap (*.pcap)", "pcap");
            abrirArchivo.setFileFilter(extension);
            abrirArchivo.setDialogTitle("Abrir archivo");
 // set selected filter
            abrirArchivo.setFileFilter(extension);
      
            int resultado = abrirArchivo.showOpenDialog(null);
            archivo = abrirArchivo.getSelectedFile();
            if(resultado==JFileChooser.APPROVE_OPTION){
                System.out.println("Archivo seleccionado: "+archivo.getAbsolutePath()); //JOPTION
            }
        }
        else{
        archivo = null;}
        
        if(this.jrbAnalizarTramas.isSelected())
        {
            File f = null;
            AnalizarTramas formularioAT = new AnalizarTramas(f, SOMEBITS, PROPERTIES, WIDTH, PROPERTIES);
            formularioAT.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            if(this.jrbGenerarTramas.isSelected())
            {
                GenerarTramas formularioGT = new GenerarTramas();
                formularioGT.setVisible(true);
                this.setVisible(false);
            }
            else
                System.out.println("Selecciona una opcion "); //JOPTION
        }
        
       
        
        
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jrbETHERNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbETHERNETActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbETHERNETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Inicio formularioInicio = new Inicio();
        formularioInicio.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAnalizarGenerar;
    private javax.swing.ButtonGroup bgOpcionesETHERNET;
    private javax.swing.ButtonGroup bgVueloCargarArchivo;
    private javax.swing.JPanel jPanelFiltrosETHERNET;
    private javax.swing.JPanel jPanelParametros;
    private javax.swing.JPanel jPanelVueloArchivo;
    private javax.swing.JPanel jPanleFiltros;
    private javax.swing.JButton jbAceptar;
    private javax.swing.ButtonGroup jbgETHERNETIEEE;
    private javax.swing.JComboBox<String> jcbModo;
    private javax.swing.JLabel jlFiltrosCaptura;
    private javax.swing.JLabel jlModo;
    private javax.swing.JLabel jlNumPaquetes;
    private javax.swing.JLabel jlParametros;
    private javax.swing.JLabel jlTamMax;
    private javax.swing.JLabel jlTiempo;
    private javax.swing.JRadioButton jrbARP;
    private javax.swing.JRadioButton jrbAnalizarTramas;
    private javax.swing.JRadioButton jrbArchivo;
    private javax.swing.JRadioButton jrbETHERNET;
    private javax.swing.JRadioButton jrbGenerarTramas;
    private javax.swing.JRadioButton jrbIEE802;
    private javax.swing.JRadioButton jrbIP;
    private javax.swing.JRadioButton jrbVuelo;
    private javax.swing.JTextField jtfNumPaquetes;
    private javax.swing.JTextField jtfTamMax;
    private javax.swing.JTextField jtfTiempo;
    private javax.swing.JLabel lbl2CV10;
    private javax.swing.JLabel lblEGD;
    private javax.swing.JLabel lblESCOM;
    private javax.swing.JLabel lblIPN;
    private javax.swing.JLabel lblInstrucciones1;
    private javax.swing.JLabel lblOVI;
    private javax.swing.JLabel lblSniffer;
    // End of variables declaration//GEN-END:variables
}
